<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>XpSearch.FacetSpike</RootNamespace>
    <AssemblyName>XpSearch.FacetSpike</AssemblyName>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Lucene.Net" />
    <PackageReference Include="Lucene.Net.Analysis.Common" />
    <PackageReference Include="Lucene.Net.Facet" />
  </ItemGroup>

</Project>
