// Generates the C# and TypeScript contract types from contract/xpsearch-api.schema.json.
//   node scripts/contract.mjs            regenerate in place  (npm run contract:gen)
//   node scripts/contract.mjs --check    regenerate into a temp dir and fail on drift (npm run contract:check)
import { execFileSync } from 'node:child_process';
import { mkdtempSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const clientDir = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const schemaPath = resolve(clientDir, '../../contract/xpsearch-api.schema.json');
// Run quicktype's JS entry point with this node, not the .bin shim: Node 24 refuses to spawn a
// .cmd file without a shell on Windows (EINVAL).
const quicktype = join(clientDir, 'node_modules', 'quicktype', 'dist', 'index.js');

const banner = (comment) => [
  `${comment} <auto-generated>`,
  `${comment}     Generated from contract/xpsearch-api.schema.json by quicktype. DO NOT EDIT.`,
  `${comment}     Regenerate with: npm run contract:gen  (in src/XpSearch.Client)`,
  `${comment}     CI guard: npm run contract:check`,
  `${comment} </auto-generated>`,
].join('\n');

// XpSearch.Core is a published package, so its public API must be the contract types and nothing
// else. `--features attributes-only` drops quicktype's FromJson/ToJson plumbing; these three edits
// deal with what it still emits as public. Each one throws if its anchor is gone, so a quicktype
// upgrade that changes the output fails the build instead of quietly widening the public surface.
const csharpEdits = [
  {
    why: 'the placeholder top-level type is never sent on the wire',
    from: 'public partial class XpSearchContract',
    to: 'internal partial class XpSearchContract',
  },
  {
    why: 'unused date converter, emitted for every C# target',
    from: 'public class DateOnlyConverter',
    to: 'internal class DateOnlyConverter',
  },
  {
    why: 'unused time converter, emitted for every C# target',
    from: 'public class TimeOnlyConverter',
    to: 'internal class TimeOnlyConverter',
  },
  {
    // A converter that cannot read a wire value throws a bare Exception, which ASP.NET Core would
    // answer with a 500. JsonException is what a malformed body actually is, and what minimal APIs
    // turn into a 400 before the handler ever runs.
    why: 'a bad enum value on the wire is a bad request, not a server fault',
    all: true,
    from: 'throw new Exception("Cannot ',
    to: 'throw new JsonException("Cannot ',
  },
  {
    // quicktype has no data for `additionalProperties: true`, so it falls back to `object`.
    // JsonElement is what System.Text.Json actually puts in there, and what the projection
    // stage builds, so the property is typed as the thing it holds.
    why: 'the open attributes bag is the one place the schema cannot name a value type',
    from: 'public Dictionary<string, object> Attributes { get; set; }',
    to: 'public Dictionary<string, JsonElement> Attributes { get; set; }',
  },
  // attributes-only emits a converter per string enum (mapping "click", "or", "lte", ...) but
  // attaches it to nothing, so a default JsonSerializer would write the enum as 0/1. Attaching
  // each converter to its enum makes every use round-trip the wire strings, options or no
  // options. The pragma is scoped to the enum, not the file: CS1591 (missing XML doc) is
  // otherwise a real signal here, and every other emitted member carries its schema
  // description. JSON Schema has nowhere to describe an individual enum value, so these
  // members cannot be documented.
  ...['EventType { Click, Conversion }', 'FacetOperator { And, Or }', 'NumericOperator { Eq, Gt, Gte, Lt, Lte, Ne }'].map(
    (declaration) => ({
      why: 'attributes-only leaves the enum converter unattached',
      from: `    public enum ${declaration};`,
      to: [
        '#pragma warning disable CS1591 // no way to document an individual enum member from JSON Schema',
        `    [JsonConverter(typeof(${declaration.split(' ')[0]}Converter))]`,
        `    public enum ${declaration};`,
        '#pragma warning restore CS1591',
      ].join('\n'),
    })
  ),
];

const targets = [
  {
    name: 'C#',
    out: resolve(clientDir, '../XpSearch.Core/Contract/Generated/XpSearchContract.g.cs'),
    args: [
      '--lang', 'cs', '--framework', 'SystemTextJson', '--csharp-version', '8',
      '--features', 'attributes-only', '--namespace', 'XpSearch.Core.Contract',
    ],
    // attributes-only emits no file-level directives of its own, so the header supplies them:
    // #nullable enable because the properties carry nullable annotations (CS8669), and CS8618
    // because a required wire field is left uninitialized until the deserializer sets it.
    header: `${banner('//')}\n#nullable enable\n#pragma warning disable CS8618\n`,
    edits: csharpEdits,
  },
  {
    name: 'TypeScript',
    out: resolve(clientDir, 'src/contract/generated.ts'),
    args: ['--lang', 'ts', '--just-types', '--acronym-style', 'original'],
    header: `${banner('//')}\n`,
    edits: [],
  },
];

function generate(target, outFile) {
  execFileSync(process.execPath, [
    quicktype,
    '--src-lang', 'schema', '--src', schemaPath,
    '--top-level', 'XpSearchContract', ...target.args, '-o', outFile,
  ], { cwd: clientDir, stdio: ['ignore', 'inherit', 'inherit'] });
  let text = readFileSync(outFile, 'utf8').replace(/\r\n/g, '\n');
  for (const edit of target.edits) {
    if (!text.includes(edit.from)) {
      throw new Error(`${target.name}: quicktype no longer emits \`${edit.from}\` (edit reason: ${edit.why}). Review the generated output before removing this edit.`);
    }
    text = edit.all ? text.replaceAll(edit.from, edit.to) : text.replace(edit.from, edit.to);
  }
  return target.header + text;
}

/**
 * The contract's `Result` is closed - `id`, `score`, `attributes`, `highlights`, `ranking` and
 * nothing else (ADR-0010) - and `attributes` is the single open object inside it. Both halves
 * are asserted here because a schema edit that reopened the result, or closed the attribute
 * bag, would still generate cleanly and only fail much later.
 */
function assertResultShape(lang, text) {
  const schema = JSON.parse(readFileSync(schemaPath, 'utf8'));
  const expected = Object.keys(schema.$defs.Result.properties).sort().join(', ');
  // The generated `Result` body only: everything from the declaration to its closing brace.
  // Scoped, so a property removed from Result but still present on another type is caught.
  const anchor = lang === 'C#' ? 'public partial class Result\n' : 'export interface Result {';
  const body = text.slice(text.indexOf(anchor)).split('\n    }')[0].split('\n}')[0];
  const declared = lang === 'C#'
    ? [...body.matchAll(/\[JsonPropertyName\("([^"]+)"\)]/g)].map((m) => m[1])
    : [...body.matchAll(/^\s{4}(\w+)\??:/gm)].map((m) => m[1]);
  if (declared.sort().join(', ') !== expected) {
    throw new Error(`${lang}: generated Result declares [${declared.join(', ')}] but the schema's Result.properties are [${expected}].`);
  }
  if (/\[JsonExtensionData]|\[property: string]: unknown;/.test(body)) {
    throw new Error(`${lang}: generated Result is an open object; the contract requires a closed one.`);
  }
  const attributes = lang === 'C#'
    ? 'public Dictionary<string, JsonElement> Attributes'
    : 'attributes: { [key: string]: unknown }';
  if (!body.includes(attributes)) {
    throw new Error(`${lang}: Result.attributes is no longer the open bag (\`${attributes}\` is gone).`);
  }
}

/**
 * The published surface of each language binding: the wire types and nothing else. XpSearch.Core
 * is a NuGet package, so a quicktype upgrade that made its serializer plumbing public would
 * silently widen the API; the C# half of this assertion is what stops that.
 */
const PUBLIC_TYPES = [
  'EventRequest', 'EventType', 'FacetFilter', 'FacetOperator', 'FacetValue', 'Filters',
  'HighlightOptions', 'NumericFilter', 'NumericOperator', 'RankingInfo', 'Result',
  'SearchRequest', 'SearchResponse', 'SuggestRequest', 'SuggestResponse', 'Suggestion',
];

function assertPublicSurface(lang, text) {
  const declared = lang === 'C#'
    ? [...text.matchAll(/^\s*public (?:partial class|enum) (\w+)/gm)].map((m) => m[1])
    : [...text.matchAll(/^export (?:interface|type) (\w+)/gm)].map((m) => m[1]);
  // XpSearchContract is the generator's top-level placeholder: internal in C#, unavoidable in TS.
  const actual = declared.filter((name) => name !== 'XpSearchContract').sort().join(', ');
  if (actual !== PUBLIC_TYPES.join(', ')) {
    throw new Error(`${lang}: public contract types are [${actual}] but should be [${PUBLIC_TYPES.join(', ')}].`);
  }
}

const check = process.argv.includes('--check');
const scratch = check ? mkdtempSync(join(tmpdir(), 'xpsearch-contract-')) : null;
let drift = false;

for (const target of targets) {
  const outFile = check ? join(scratch, target.out.split(/[\\/]/).pop()) : target.out;
  if (!check) { mkdirSync(dirname(outFile), { recursive: true }); }
  const text = generate(target, outFile);
  assertResultShape(target.name, text);
  assertPublicSurface(target.name, text);
  if (check) {
    const current = readFileSync(target.out, 'utf8').replace(/\r\n/g, '\n');
    if (current !== text) {
      drift = true;
      const currentLines = current.split('\n');
      const newLines = text.split('\n');
      const i = newLines.findIndex((l, n) => l !== currentLines[n]);
      console.error(`DRIFT in ${target.out}\n  first difference at line ${i + 1}:\n  checked in: ${currentLines[i]}\n  generated : ${newLines[i]}`);
    } else {
      console.log(`up to date: ${target.out}`);
    }
  } else {
    writeFileSync(outFile, text);
    console.log(`wrote: ${outFile}`);
  }
}

if (drift) {
  console.error('\nContract outputs are out of date. Run `npm run contract:gen` and commit the result.');
  process.exit(1);
}
