// Generates the C# and TypeScript contract types from contract/xpsearch-api.schema.json.
//   node scripts/contract.mjs            regenerate in place  (npm run contract:gen)
//   node scripts/contract.mjs --check    regenerate into a temp dir and fail on drift (npm run contract:check)
import { execFileSync } from 'node:child_process';
import { mkdtempSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const clientDir = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const schemaPath = resolve(clientDir, '../../contract/xpsearch-api.schema.json');
// Run quicktype's JS entry point with this node, not the .bin shim: Node 24 refuses to spawn a
// .cmd file without a shell on Windows (EINVAL).
const quicktype = join(clientDir, 'node_modules', 'quicktype', 'dist', 'index.js');

const banner = (comment) => [
  `${comment} <auto-generated>`,
  `${comment}     Generated from contract/xpsearch-api.schema.json by quicktype. DO NOT EDIT.`,
  `${comment}     Regenerate with: npm run contract:gen  (in src/XpSearch.Client)`,
  `${comment}     CI guard: npm run contract:check`,
  `${comment} </auto-generated>`,
].join('\n');

const targets = [
  {
    name: 'C#',
    out: resolve(clientDir, '../XpSearch.Core/Contract/Generated/XpSearchContract.g.cs'),
    args: ['--lang', 'cs', '--framework', 'SystemTextJson', '--csharp-version', '8', '--namespace', 'XpSearch.Core.Contract'],
    // CS1591: quicktype's serializer plumbing (Converter, Serialize, ...) carries no XML docs and
    // the library builds with GenerateDocumentationFile + TreatWarningsAsErrors.
    header: `${banner('//')}\n#pragma warning disable CS1591\n`,
  },
  {
    name: 'TypeScript',
    out: resolve(clientDir, 'src/contract/generated.ts'),
    args: ['--lang', 'ts', '--just-types', '--acronym-style', 'original'],
    header: `${banner('//')}\n`,
  },
];

function generate(target, outFile) {
  execFileSync(process.execPath, [
    quicktype,
    '--src-lang', 'schema', '--src', schemaPath,
    '--top-level', 'XpSearchContract', ...target.args, '-o', outFile,
  ], { cwd: clientDir, stdio: ['ignore', 'inherit', 'inherit'] });
  return target.header + readFileSync(outFile, 'utf8').replace(/\r\n/g, '\n');
}

// The contract's Hit is an open object (spec 4.2): reserved members plus any retrieved attribute.
// quicktype honours `additionalProperties: true` in TypeScript (index signature) but NOT in C#,
// where the open half is hand-written as a partial class in Contract/Hit.cs.
function assertHitStaysOpen(lang, text) {
  const schema = JSON.parse(readFileSync(schemaPath, 'utf8'));
  const names = Object.keys(schema.$defs.Hit.properties);
  // The TypeScript `Hit` body: everything between `export interface Hit {` and the closing brace.
  const tsHit = text.slice(text.indexOf('export interface Hit {')).split('\n}')[0];
  const missing = names.filter((n) => (lang === 'C#'
    ? !text.includes(`[JsonPropertyName("${n}")]`)
    : !new RegExp(`^\\s*${n}\\??:`, 'm').test(tsHit)));
  if (missing.length) {
    throw new Error(`${lang}: generated Hit is missing schema properties: ${missing.join(', ')}`);
  }
  if (lang === 'C#') {
    if (!/public partial class Hit\b/.test(text)) {
      throw new Error('C#: Hit is no longer a partial class, so Contract/Hit.cs can no longer add [JsonExtensionData].');
    }
    const handWritten = readFileSync(resolve(clientDir, '../XpSearch.Core/Contract/Hit.cs'), 'utf8');
    if (!handWritten.includes('[JsonExtensionData]')) {
      throw new Error('C#: Contract/Hit.cs no longer carries [JsonExtensionData]; Hit would be a closed object.');
    }
  } else if (!tsHit.includes('[property: string]: unknown;')) {
    throw new Error('TypeScript: generated Hit lost its index signature; it would be a closed object.');
  }
}

const check = process.argv.includes('--check');
const scratch = check ? mkdtempSync(join(tmpdir(), 'xpsearch-contract-')) : null;
let drift = false;

for (const target of targets) {
  const outFile = check ? join(scratch, target.out.split(/[\\/]/).pop()) : target.out;
  if (!check) { mkdirSync(dirname(outFile), { recursive: true }); }
  const text = generate(target, outFile);
  assertHitStaysOpen(target.name, text);
  if (check) {
    const current = readFileSync(target.out, 'utf8').replace(/\r\n/g, '\n');
    if (current !== text) {
      drift = true;
      const currentLines = current.split('\n');
      const newLines = text.split('\n');
      const i = newLines.findIndex((l, n) => l !== currentLines[n]);
      console.error(`DRIFT in ${target.out}\n  first difference at line ${i + 1}:\n  checked in: ${currentLines[i]}\n  generated : ${newLines[i]}`);
    } else {
      console.log(`up to date: ${target.out}`);
    }
  } else {
    writeFileSync(outFile, text);
    console.log(`wrote: ${outFile}`);
  }
}

if (drift) {
  console.error('\nContract outputs are out of date. Run `npm run contract:gen` and commit the result.');
  process.exit(1);
}
