// Generates the C# and TypeScript contract types from contract/xpsearch-api.schema.json.
//   node scripts/contract.mjs            regenerate in place  (npm run contract:gen)
//   node scripts/contract.mjs --check    regenerate into a temp dir and fail on drift (npm run contract:check)
import { execFileSync } from 'node:child_process';
import { mkdtempSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const clientDir = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const schemaPath = resolve(clientDir, '../../contract/xpsearch-api.schema.json');
// Run quicktype's JS entry point with this node, not the .bin shim: Node 24 refuses to spawn a
// .cmd file without a shell on Windows (EINVAL).
const quicktype = join(clientDir, 'node_modules', 'quicktype', 'dist', 'index.js');

const banner = (comment) => [
  `${comment} <auto-generated>`,
  `${comment}     Generated from contract/xpsearch-api.schema.json by quicktype. DO NOT EDIT.`,
  `${comment}     Regenerate with: npm run contract:gen  (in src/XpSearch.Client)`,
  `${comment}     CI guard: npm run contract:check`,
  `${comment} </auto-generated>`,
].join('\n');

// XpSearch.Core is a published package, so its public API must be the contract types and nothing
// else. `--features attributes-only` drops quicktype's FromJson/ToJson plumbing; these three edits
// deal with what it still emits as public. Each one throws if its anchor is gone, so a quicktype
// upgrade that changes the output fails the build instead of quietly widening the public surface.
const csharpEdits = [
  {
    why: 'the placeholder top-level type is never sent on the wire',
    from: 'public partial class XpSearchContract',
    to: 'internal partial class XpSearchContract',
  },
  {
    why: 'unused date converter, emitted for every C# target',
    from: 'public class DateOnlyConverter',
    to: 'internal class DateOnlyConverter',
  },
  {
    why: 'unused time converter, emitted for every C# target',
    from: 'public class TimeOnlyConverter',
    to: 'internal class TimeOnlyConverter',
  },
  {
    // attributes-only emits EventTypeConverter (which maps "click"/"conversion") but attaches it to
    // nothing, so a default JsonSerializer would write the enum as 0/1. Attaching it to the enum
    // itself makes every use of EventType round-trip the wire strings, options or no options.
    // The pragma is scoped to the enum, not the file: CS1591 (missing XML doc) is otherwise a real
    // signal here, and every other emitted member carries its schema description. JSON Schema has
    // nowhere to describe an individual enum value, so these two members cannot be documented.
    why: 'attributes-only leaves the enum converter unattached',
    from: '    public enum EventType { Click, Conversion };',
    to: [
      '#pragma warning disable CS1591 // no way to document an individual enum member from JSON Schema',
      '    [JsonConverter(typeof(EventTypeConverter))]',
      '    public enum EventType { Click, Conversion };',
      '#pragma warning restore CS1591',
    ].join('\n'),
  },
];

const targets = [
  {
    name: 'C#',
    out: resolve(clientDir, '../XpSearch.Core/Contract/Generated/XpSearchContract.g.cs'),
    args: [
      '--lang', 'cs', '--framework', 'SystemTextJson', '--csharp-version', '8',
      '--features', 'attributes-only', '--namespace', 'XpSearch.Core.Contract',
    ],
    // attributes-only emits no file-level directives of its own, so the header supplies them:
    // #nullable enable because the properties carry nullable annotations (CS8669), and CS8618
    // because a required wire field is left uninitialized until the deserializer sets it.
    header: `${banner('//')}\n#nullable enable\n#pragma warning disable CS8618\n`,
    edits: csharpEdits,
  },
  {
    name: 'TypeScript',
    out: resolve(clientDir, 'src/contract/generated.ts'),
    args: ['--lang', 'ts', '--just-types', '--acronym-style', 'original'],
    header: `${banner('//')}\n`,
    edits: [],
  },
];

function generate(target, outFile) {
  execFileSync(process.execPath, [
    quicktype,
    '--src-lang', 'schema', '--src', schemaPath,
    '--top-level', 'XpSearchContract', ...target.args, '-o', outFile,
  ], { cwd: clientDir, stdio: ['ignore', 'inherit', 'inherit'] });
  let text = readFileSync(outFile, 'utf8').replace(/\r\n/g, '\n');
  for (const edit of target.edits) {
    if (!text.includes(edit.from)) {
      throw new Error(`${target.name}: quicktype no longer emits \`${edit.from}\` (edit reason: ${edit.why}). Review the generated output before removing this edit.`);
    }
    text = text.replace(edit.from, edit.to);
  }
  return target.header + text;
}

// The contract's Hit is an open object (spec 4.2): reserved members plus any retrieved attribute.
// quicktype honours `additionalProperties: true` in TypeScript (index signature) but NOT in C#,
// where the open half is hand-written as a partial class in Contract/Hit.cs.
function assertHitStaysOpen(lang, text) {
  const schema = JSON.parse(readFileSync(schemaPath, 'utf8'));
  const names = Object.keys(schema.$defs.Hit.properties);
  // The generated `Hit` body only: everything from the declaration to its closing brace. Scoped,
  // so that a property removed from Hit but still present on another type is still caught.
  const anchor = lang === 'C#' ? 'public partial class Hit\n' : 'export interface Hit {';
  const hitBody = text.slice(text.indexOf(anchor)).split('\n    }')[0].split('\n}')[0];
  const declared = lang === 'C#'
    ? [...hitBody.matchAll(/\[JsonPropertyName\("([^"]+)"\)]/g)].map((m) => m[1])
    : [...hitBody.matchAll(/^\s{4}(\w+)\??:/gm)].map((m) => m[1]);
  const expected = [...names].sort().join(', ');
  if (declared.sort().join(', ') !== expected) {
    throw new Error(`${lang}: generated Hit declares [${declared.join(', ')}] but the schema's Hit.properties are [${expected}].`);
  }
  if (lang === 'C#') {
    if (!/public partial class Hit\b/.test(text)) {
      throw new Error('C#: Hit is no longer a partial class, so Contract/Hit.cs can no longer add [JsonExtensionData].');
    }
    const handWritten = readFileSync(resolve(clientDir, '../XpSearch.Core/Contract/Hit.cs'), 'utf8');
    if (!handWritten.includes('[JsonExtensionData]')) {
      throw new Error('C#: Contract/Hit.cs no longer carries [JsonExtensionData]; Hit would be a closed object.');
    }
  } else if (!hitBody.includes('[property: string]: unknown;')) {
    throw new Error('TypeScript: generated Hit lost its index signature; it would be a closed object.');
  }
}

const check = process.argv.includes('--check');
const scratch = check ? mkdtempSync(join(tmpdir(), 'xpsearch-contract-')) : null;
let drift = false;

for (const target of targets) {
  const outFile = check ? join(scratch, target.out.split(/[\\/]/).pop()) : target.out;
  if (!check) { mkdirSync(dirname(outFile), { recursive: true }); }
  const text = generate(target, outFile);
  assertHitStaysOpen(target.name, text);
  if (check) {
    const current = readFileSync(target.out, 'utf8').replace(/\r\n/g, '\n');
    if (current !== text) {
      drift = true;
      const currentLines = current.split('\n');
      const newLines = text.split('\n');
      const i = newLines.findIndex((l, n) => l !== currentLines[n]);
      console.error(`DRIFT in ${target.out}\n  first difference at line ${i + 1}:\n  checked in: ${currentLines[i]}\n  generated : ${newLines[i]}`);
    } else {
      console.log(`up to date: ${target.out}`);
    }
  } else {
    writeFileSync(outFile, text);
    console.log(`wrote: ${outFile}`);
  }
}

if (drift) {
  console.error('\nContract outputs are out of date. Run `npm run contract:gen` and commit the result.');
  process.exit(1);
}
