// <auto-generated>
//     Generated from contract/xpsearch-api.schema.json by quicktype. DO NOT EDIT.
//     Regenerate with: npm run contract:gen  (in src/XpSearch.Client)
//     CI guard: npm run contract:check
// </auto-generated>
/**
 * Wire contract for the Xperience Search HTTP API (spec 4.2, 4.3, 9.1). This schema is the
 * single source of truth: the C# DTOs (XpSearch.Core.Contract) and the TypeScript types
 * (@yourco/xperience-search) are generated from it and must never be hand-edited. Field
 * names deliberately mirror Algolia's request/response shape. That is a documented feature,
 * not an accident: a team moving off Algolia can swap the transport and keep most of their
 * UI code. Endpoints: POST /api/xpsearch/query (SearchRequest -> SearchResponse), POST
 * /api/xpsearch/suggest (SuggestRequest -> SuggestResponse), POST /api/xpsearch/events
 * (EventRequest -> 202 Accepted with an empty body; there is no event response type). Every
 * response carries the header X-XpSearch-Api-Version: 1; the contract version is the semver
 * major of both the NuGet and npm packages, and routes never carry a version segment.
 * Errors are RFC 9457 Problem Details (application/problem+json) as produced by ASP.NET
 * Core's ProblemDetails - see https://learn.microsoft.com/aspnet/core/web-api/handle-errors
 * - and are deliberately not redefined here.
 */
export interface XpSearchContract {
    /**
     * Placeholder property so the code generator emits EventRequest. Never sent on the wire.
     */
    eventRequest?: EventRequest;
    /**
     * Placeholder property so the code generator emits SearchRequest. Never sent on the wire.
     */
    searchRequest?: SearchRequest;
    /**
     * Placeholder property so the code generator emits SearchResponse. Never sent on the wire.
     */
    searchResponse?: SearchResponse;
    /**
     * Placeholder property so the code generator emits SuggestRequest. Never sent on the wire.
     */
    suggestRequest?: SuggestRequest;
    /**
     * Placeholder property so the code generator emits SuggestResponse. Never sent on the wire.
     */
    suggestResponse?: SuggestResponse;
}

/**
 * Placeholder property so the code generator emits EventRequest. Never sent on the wire.
 *
 * Body of POST /api/xpsearch/events (spec 4.3, 9.1). The endpoint answers 202 Accepted with
 * an empty body, so there is no response type. Logging is consent-gated and best-effort: a
 * 202 means the event was accepted, not that an activity was written.
 */
export interface EventRequest {
    /**
     * Required. "click" when the user opens a result, "conversion" when the developer signals a
     * goal reached after a search.
     */
    eventType: EventType;
    /**
     * Code name of the index the search ran against. Omit to have the server resolve it from
     * queryId.
     */
    index?: string;
    /**
     * Required. objectID of the hit the event is about.
     */
    objectID: string;
    /**
     * One-based position of the hit in the result list. Required when eventType is "click",
     * ignored for "conversion".
     */
    position?: number;
    /**
     * Required. The queryId from the SearchResponse that produced the hit. This is what
     * correlates the event back to its search.
     */
    queryId: string;
}

/**
 * Required. "click" when the user opens a result, "conversion" when the developer signals a
 * goal reached after a search.
 */
export type EventType = "click" | "conversion";

/**
 * Placeholder property so the code generator emits SearchRequest. Never sent on the wire.
 *
 * Body of POST /api/xpsearch/query.
 */
export interface SearchRequest {
    /**
     * Attributes to project onto each hit. Omit to return the index's configured default
     * projection. objectID is always returned.
     */
    attributesToRetrieve?: string[];
    /**
     * When true, each hit carries _rankingInfo explaining its score. Defaults to false. Used by
     * the admin query tester (spec 8.4).
     */
    explain?: boolean;
    /**
     * Facet refinements. The outer array is ANDed, each inner array is ORed:
     * [["contentType:Article","contentType:Product"],["tags:coffee"]] means (Article OR
     * Product) AND coffee.
     */
    facetFilters?: Array<string[]>;
    /**
     * Attributes to compute facet counts for. Counts come back in SearchResponse.facets.
     */
    facets?: string[];
    /**
     * Highlighting options. Omit to use the defaults.
     */
    highlight?: HighlightOptions;
    /**
     * Number of hits per page. Defaults to 20. The maximum of 1000 is a contract ceiling; the
     * effective maximum is enforced server-side and may be lower per configuration.
     */
    hitsPerPage?: number;
    /**
     * Required. Code name of the Lucene index to search, as registered in the Xperience Search
     * application. Must be non-empty; validated server-side, which answers 400 Problem Details
     * when it is not.
     */
    index: string;
    /**
     * Language code of the content to search, for example "en". Omit to use the current
     * request's language.
     */
    language?: string;
    /**
     * Numeric refinements, ANDed together. Grammar: attribute, operator, number - where the
     * attribute starts with a letter or underscore and may contain word characters and dots,
     * the operator is one of <=, >=, <, >, =, != and the number is an optionally negative
     * integer or decimal. Whitespace around the operator is allowed. Dates are compared as Unix
     * epoch seconds.
     */
    numericFilters?: string[];
    /**
     * Zero-based page number. Defaults to 0.
     */
    page?: number;
    /**
     * Free-text query. An empty string (the default) means match all documents.
     */
    query?: string;
    /**
     * Client-supplied correlation id echoed back on the response and used to tie click and
     * conversion events to this search. Omit to have the server generate one.
     */
    queryId?: string;
    /**
     * Sort order: the literal "relevance" (the default, score descending) or a sort key
     * configured for the index.
     */
    sort?: string;
}

/**
 * Highlighting options. Omit to use the defaults.
 *
 * Per-request highlighting configuration.
 */
export interface HighlightOptions {
    /**
     * Fields to produce highlighted snippets for. Results land in Hit._highlights.
     */
    fields?: string[];
    /**
     * Markup inserted after each match. Defaults to "</mark>".
     */
    postTag?: string;
    /**
     * Markup inserted before each match. Defaults to "<mark>".
     */
    preTag?: string;
    /**
     * Maximum snippet length in characters. Defaults to 200.
     */
    snippetLength?: number;
}

/**
 * Placeholder property so the code generator emits SearchResponse. Never sent on the wire.
 *
 * Body of a 200 response from POST /api/xpsearch/query.
 */
export interface SearchResponse {
    /**
     * Facet counts, keyed by attribute name and then by facet value. Only attributes listed in
     * SearchRequest.facets appear, and only values with a non-zero count in the current result
     * set.
     */
    facets?: { [key: string]: { [key: string]: number } };
    /**
     * The hits on the requested page, in ranked order.
     */
    hits: Hit[];
    /**
     * Page size that was applied, after server-side clamping.
     */
    hitsPerPage: number;
    /**
     * Total number of matching documents across all pages.
     */
    nbHits: number;
    /**
     * Total number of pages available.
     */
    nbPages: number;
    /**
     * Zero-based number of the page that was returned.
     */
    page: number;
    /**
     * Server-side processing time in milliseconds, excluding network time.
     */
    processingTimeMs: number;
    /**
     * Correlation id for this search. Echoes SearchRequest.queryId when supplied, otherwise
     * server-generated. Send it back on click and conversion events.
     */
    queryId?: string;
}

/**
 * One search result. Deliberately an open object: objectID and the underscore-prefixed
 * members are reserved by the contract, and every other property is a retrieved document
 * attribute (title, url, summary, image, ...) whose set is decided by
 * SearchRequest.attributesToRetrieve and the index configuration.
 */
export interface Hit {
    /**
     * Highlighted snippets keyed by field name. Present only for fields requested in
     * SearchRequest.highlight.fields. Values are HTML-encoded content with the configured pre
     * and post tags inserted, so they are safe to render as HTML.
     */
    _highlights?: { [key: string]: string };
    /**
     * Score explanation. Present only when SearchRequest.explain is true; absent otherwise.
     */
    _rankingInfo?: RankingInfo;
    /**
     * Final relevance score after boosts and rules. Higher is more relevant; values are only
     * comparable within one response.
     */
    _score?: number;
    /**
     * Required. Stable unique identifier of the indexed document. Send it back on click and
     * conversion events.
     */
    objectID: string;
    /**
     * Canonical link to the document, when the index projects one. Always root-relative
     * ("/articles/espresso-basics") or absolute
     * ("https://example.com/articles/espresso-basics"); never the app-relative "~/..." form
     * Xperience's URL retriever returns - the server resolves that before it reaches the wire.
     */
    url?: string;
    [property: string]: unknown;
}

/**
 * Score explanation. Present only when SearchRequest.explain is true; absent otherwise.
 *
 * Per-hit score explanation, returned only when SearchRequest.explain is true (spec 4.2,
 * 8.4).
 */
export interface RankingInfo {
    /**
     * Boosts and rules that changed the score or position, in application order.
     */
    appliedBoosts?: string[];
    /**
     * Lucene score before any boost rule was applied.
     */
    baseScore?: number;
    /**
     * One-based position of this hit in the final ranking, across all pages.
     */
    position?: number;
}

/**
 * Placeholder property so the code generator emits SuggestRequest. Never sent on the wire.
 *
 * Body of POST /api/xpsearch/suggest. Whether an index answers with query suggestions or
 * with federated hits is server-side per-index configuration, not a request field.
 */
export interface SuggestRequest {
    /**
     * Required. Code name of the Lucene index to suggest from. Must be non-empty; validated
     * server-side, which answers 400 Problem Details when it is not.
     */
    index: string;
    /**
     * Language code to suggest in, for example "en". Omit to use the current request's language.
     */
    language?: string;
    /**
     * Maximum number of suggestions to return. Defaults to 5. Enforced server-side.
     */
    maxItems?: number;
    /**
     * Required. The partial input to prefix-match. May be an empty string, which yields no
     * suggestions.
     */
    query: string;
}

/**
 * Placeholder property so the code generator emits SuggestResponse. Never sent on the
 * wire.
 *
 * Body of a 200 response from POST /api/xpsearch/suggest.
 */
export interface SuggestResponse {
    /**
     * Suggestions in display order, at most SuggestRequest.maxItems of them.
     */
    suggestions: Suggestion[];
}

/**
 * One autocomplete entry.
 */
export interface Suggestion {
    /**
     * Documents behind this suggestion, present only for indexes configured in federated-hits
     * mode.
     */
    hits?: Hit[];
    /**
     * Required. The text to display and, for a query suggestion, to search for when picked.
     */
    text: string;
    /**
     * Link to follow when the suggestion is picked, present only for indexes configured in
     * federated-hits mode. Root-relative or absolute, never the app-relative "~/..." form.
     */
    url?: string;
}
