// <auto-generated>
//     Generated from contract/xpsearch-ingestion.schema.json by quicktype. DO NOT EDIT.
//     Regenerate with: npm run contract:gen  (in src/XpSearch.Client)
//     CI guard: npm run contract:check
// </auto-generated>
/**
 * Wire contract for the Xperience Search ingestion API (spec 10.1 - 10.4, 10.6, as amended
 * by ADR-0010: documents are addressed by id, timings are tookMs). This schema is the
 * single source of truth: the C# DTOs (XpSearch.Ingestion.Contract) and the TypeScript
 * types are generated from it and must never be hand-edited. Endpoints, all under
 * /api/xpsearch/admin/ and all authenticated with a Bearer API key (spec 10.4): POST
 * indexes/{index}/documents (UpsertRequest -> UpsertResponse), PATCH
 * indexes/{index}/documents/{id} (PatchRequest -> UpsertResponse), DELETE
 * indexes/{index}/documents/{id} (-> DeleteResponse), POST indexes/{index}/documents/delete
 * (BatchDeleteRequest -> DeleteResponse), POST indexes/{index}/clear (-> DeleteResponse),
 * POST indexes/{index}/rebuild (-> UpsertResponse with taskId), GET indexes/{index}/status
 * (-> IndexStatus), GET indexes (-> IndexListResponse). Every response carries the header
 * X-XpSearch-Api-Version: 1. Errors are RFC 9457 Problem Details as produced by ASP.NET
 * Core and are deliberately not redefined here; per-document failures are not errors of the
 * request and come back in UpsertResponse.errors.
 */
export interface XpSearchIngestionContract {
    /**
     * Placeholder property so the code generator emits BatchDeleteRequest. Never sent on the
     * wire.
     */
    batchDeleteRequest?: BatchDeleteRequest;
    /**
     * Placeholder property so the code generator emits DeleteResponse. Never sent on the wire.
     */
    deleteResponse?: DeleteResponse;
    /**
     * Placeholder property so the code generator emits IndexListResponse. Never sent on the
     * wire.
     */
    indexListResponse?: IndexListResponse;
    /**
     * Placeholder property so the code generator emits IndexStatus. Never sent on the wire.
     */
    indexStatus?: IndexStatus;
    /**
     * Placeholder property so the code generator emits PatchRequest. Never sent on the wire.
     */
    patchRequest?: PatchRequest;
    /**
     * Placeholder property so the code generator emits UpsertRequest. Never sent on the wire.
     */
    upsertRequest?: UpsertRequest;
    /**
     * Placeholder property so the code generator emits UpsertResponse. Never sent on the wire.
     */
    upsertResponse?: UpsertResponse;
}

/**
 * Placeholder property so the code generator emits BatchDeleteRequest. Never sent on the
 * wire.
 *
 * Body of POST /api/xpsearch/admin/indexes/{index}/documents/delete. Exactly one of ids and
 * filter must be present.
 */
export interface BatchDeleteRequest {
    /**
     * Delete every document matching the filter instead of naming ids.
     */
    filter?: DeleteFilter;
    /**
     * The document ids to delete.
     */
    ids?: string[];
}

/**
 * Delete every document matching the filter instead of naming ids.
 *
 * Which documents a filtered delete removes. Only provenance is filterable: a delete that
 * could match Xperience content would be a way to lose it.
 */
export interface DeleteFilter {
    /**
     * Delete every document pushed under this source. "xperience" is rejected.
     */
    source: string;
}

/**
 * Placeholder property so the code generator emits DeleteResponse. Never sent on the wire.
 *
 * Answer to a delete or a clear.
 */
export interface DeleteResponse {
    /**
     * Number of stored documents the operation removed.
     */
    deleted: number;
    /**
     * Identifier of the queued write, present when the delete was not awaited.
     */
    taskId?: string;
    /**
     * Server-side processing time in milliseconds.
     */
    tookMs: number;
}

/**
 * Placeholder property so the code generator emits IndexListResponse. Never sent on the
 * wire.
 *
 * Answer to GET /api/xpsearch/admin/indexes.
 */
export interface IndexListResponse {
    /**
     * Every registered index and the schema pushed documents are validated against.
     */
    indexes: IndexSummary[];
}

/**
 * One index and its schema.
 */
export interface IndexSummary {
    /**
     * Whether a pushed document may carry attributes the schema does not declare. False by
     * default.
     */
    allowDynamicFields: boolean;
    /**
     * Code name of the index.
     */
    name: string;
    /**
     * The fields the index accepts, detected from Xperience content types and declared in code.
     */
    schema: SchemaField[];
}

/**
 * One field of an index schema (spec 10.3).
 */
export interface SchemaField {
    /**
     * Whether the field can be filtered on with filters.facets.
     */
    facetable: boolean;
    /**
     * Attribute name, as it appears on a pushed document and in a query.
     */
    name: string;
    /**
     * Whether the field is stored and can be returned in a result's attributes.
     */
    retrievable: boolean;
    /**
     * Whether free-text queries match against the field.
     */
    searchable: boolean;
    /**
     * Whether the field can be used as a sort key.
     */
    sortable: boolean;
    /**
     * What the field holds: "string" is matched verbatim, "text" is analyzed free text, "date"
     * is Unix epoch seconds, "string[]" is a multi-valued facet dimension (an Xperience
     * taxonomy).
     */
    type: Type;
}

/**
 * What the field holds: "string" is matched verbatim, "text" is analyzed free text, "date"
 * is Unix epoch seconds, "string[]" is a multi-valued facet dimension (an Xperience
 * taxonomy).
 */
export type Type = "string" | "text" | "number" | "date" | "boolean" | "string[]";

/**
 * Placeholder property so the code generator emits IndexStatus. Never sent on the wire.
 *
 * Answer to GET /api/xpsearch/admin/indexes/{index}/status.
 */
export interface IndexStatus {
    /**
     * How many documents the index holds, and where they came from.
     */
    documents: DocumentCounts;
    /**
     * "healthy" when the index is readable and nothing is stuck, "degraded" when queued writes
     * are waiting or replaying, "unavailable" when the index cannot be read.
     */
    health: Health;
    /**
     * Code name of the index.
     */
    index: string;
    /**
     * When an external document was last written to this index, absent when none ever was.
     */
    lastWrite?: Date;
}

/**
 * How many documents the index holds, and where they came from.
 *
 * Document counts of one index.
 */
export interface DocumentCounts {
    /**
     * Number of documents per _source value, including "xperience".
     */
    bySource: { [key: string]: number };
    /**
     * Number of documents in the Lucene index, whatever their provenance.
     */
    total: number;
}

/**
 * "healthy" when the index is readable and nothing is stuck, "degraded" when queued writes
 * are waiting or replaying, "unavailable" when the index cannot be read.
 */
export type Health = "healthy" | "degraded" | "unavailable";

/**
 * Placeholder property so the code generator emits PatchRequest. Never sent on the wire.
 *
 * Body of PATCH /api/xpsearch/admin/indexes/{index}/documents/{id}: the attributes to
 * change and nothing else. Applied as read-modify-rewrite over the stored document, because
 * Lucene has no in-place update.
 */
export interface PatchRequest {
    /**
     * Reserved: the document's provenance. Present only to keep the reserved name out of the
     * attributes; changing it is rejected.
     */
    _source?: string;
    [property: string]: unknown;
}

/**
 * Placeholder property so the code generator emits UpsertRequest. Never sent on the wire.
 *
 * Body of POST /api/xpsearch/admin/indexes/{index}/documents. Upsert, not insert: a
 * document whose id already exists is replaced. Capped at 1000 documents or 10 MB per
 * request; a larger request is answered with 413 rather than truncated.
 */
export interface UpsertRequest {
    /**
     * The documents to write. Must contain at least one document.
     */
    documents: PushDocument[];
    /**
     * When true the response is not sent until the write is searchable. Defaults to false,
     * which queues the write on a background thread. A foot-gun for bulk imports: it serializes
     * the caller against index writes.
     */
    waitForIndex?: boolean;
}

/**
 * One document to write. Open by design: every property other than id and _source is an
 * attribute, validated against the index schema (spec 10.3).
 */
export interface PushDocument {
    /**
     * Reserved: the document's provenance. Defaults to the source of the API key, or to
     * "external". Never "xperience", which is reserved for content the Lucene integration
     * indexes.
     */
    _source?: string;
    /**
     * Required, caller-owned and stable. Re-pushing the same id replaces the document.
     */
    id: string;
    [property: string]: unknown;
}

/**
 * Placeholder property so the code generator emits UpsertResponse. Never sent on the wire.
 *
 * Answer to a write. A partially failed batch is still a 200: the documents that validated
 * are written and the rest are reported in errors.
 */
export interface UpsertResponse {
    /**
     * One entry per rejected document, keyed by its id and the offending field.
     */
    errors: IngestionError[];
    /**
     * Number of documents rejected by schema validation.
     */
    failed: number;
    /**
     * Number of documents accepted and persisted.
     */
    indexed: number;
    /**
     * Identifier of the queued write, present when the write was not awaited. Poll GET
     * indexes/{index}/status to see it land.
     */
    taskId?: string;
    /**
     * Server-side processing time in milliseconds.
     */
    tookMs: number;
}

/**
 * Why one document was rejected.
 */
export interface IngestionError {
    /**
     * The attribute the error belongs to, absent for document-level errors.
     */
    field?: string;
    /**
     * The document's id, absent only when the document had none.
     */
    id?: string;
    /**
     * Human-readable description of the problem.
     */
    message: string;
}
