<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>XpSearch.Core.Tests</RootNamespace>
    <AssemblyName>XpSearch.Core.Tests</AssemblyName>
    <PackageId>YourCo.Xperience.Search.Core.Tests</PackageId>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <None Update="Contract\Fixtures\*.json" CopyToOutputDirectory="PreserveNewest" />
    <None Update="Fixtures\ClassFormDefinitions\*.xml" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\XpSearch.Core\XpSearch.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit3TestAdapter" />
    <PackageReference Include="NUnit.Analyzers" />
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="Lucene.Net.Facet" />
    <PackageReference Include="Lucene.Net.Analysis.Common" />
  </ItemGroup>

</Project>
