// <auto-generated>
//     Generated from contract/xpsearch-api.schema.json by quicktype. DO NOT EDIT.
//     Regenerate with: npm run contract:gen  (in src/XpSearch.Widgets/Client)
//     CI guard: npm run contract:check
// </auto-generated>
/**
 * Wire contract for the Xperience Search HTTP API (spec 4.2, 4.3, 9.1, as amended by
 * ADR-0010). This schema is the single source of truth: the C# DTOs
 * (XpSearch.Core.Contract) and the TypeScript types (@yourco/xperience-search) are
 * generated from it and must never be hand-edited. Names and shapes are owned by this
 * product and chosen for Xperience's content model - taxonomy tags have code names and
 * titles, fields are typed - not for compatibility with any other vendor's API; a team
 * arriving from a hosted search service is served by docs/guides/migrating-from-algolia.md,
 * which is generated from contract/algolia-map.json. Endpoints: POST /api/xpsearch/query
 * (SearchRequest -> SearchResponse), POST /api/xpsearch/suggest (SuggestRequest ->
 * SuggestResponse), POST /api/xpsearch/events (EventRequest -> 202 Accepted with an empty
 * body; there is no event response type). Every response carries the header
 * X-XpSearch-Api-Version: 1; the contract version is the semver major of both the NuGet and
 * npm packages, and routes never carry a version segment. Errors are RFC 9457 Problem
 * Details (application/problem+json) as produced by ASP.NET Core's ProblemDetails - see
 * https://learn.microsoft.com/aspnet/core/web-api/handle-errors - and are deliberately not
 * redefined here.
 */
export interface XpSearchContract {
    /**
     * Placeholder property so the code generator emits EventRequest. Never sent on the wire.
     */
    eventRequest?: EventRequest;
    /**
     * Placeholder property so the code generator emits SearchRequest. Never sent on the wire.
     */
    searchRequest?: SearchRequest;
    /**
     * Placeholder property so the code generator emits SearchResponse. Never sent on the wire.
     */
    searchResponse?: SearchResponse;
    /**
     * Placeholder property so the code generator emits SuggestRequest. Never sent on the wire.
     */
    suggestRequest?: SuggestRequest;
    /**
     * Placeholder property so the code generator emits SuggestResponse. Never sent on the wire.
     */
    suggestResponse?: SuggestResponse;
}

/**
 * Placeholder property so the code generator emits EventRequest. Never sent on the wire.
 *
 * Body of POST /api/xpsearch/events (spec 4.3, 9.1). The endpoint answers 202 Accepted with
 * an empty body, so there is no response type. Logging is consent-gated and best-effort: a
 * 202 means the event was accepted, not that an activity was written.
 */
export interface EventRequest {
    /**
     * One-based position of the result in the list. Required when type is "click", ignored for
     * "conversion".
     */
    position?: number;
    /**
     * Required. The queryId from the SearchResponse that produced the result. This is what
     * correlates the event back to its search.
     */
    queryId: string;
    /**
     * Required. The id of the result the event is about.
     */
    resultId: string;
    /**
     * Required. What happened.
     */
    type: EventType;
}

/**
 * Required. What happened.
 *
 * The kind of an analytics event: "click" when the user opens a result, "conversion" when
 * the developer signals a goal reached after a search.
 */
export type EventType = "click" | "conversion";

/**
 * Placeholder property so the code generator emits SearchRequest. Never sent on the wire.
 *
 * Body of POST /api/xpsearch/query.
 */
export interface SearchRequest {
    /**
     * When true, each result carries ranking explaining its score. Defaults to false. Used by
     * the admin query tester (spec 8.4).
     */
    explain?: boolean;
    /**
     * Attributes to compute facet counts for. Counts come back in SearchResponse.facets.
     */
    facets?: string[];
    /**
     * Fields to project into each result's attributes. Omit to return the index's configured
     * default projection. The result id is always returned and is never an attribute.
     */
    fields?: string[];
    /**
     * Structured refinements. Omit to search unfiltered.
     */
    filters?: Filters;
    /**
     * Highlighting options. Omit to use the defaults.
     */
    highlight?: HighlightOptions;
    /**
     * Required. Code name of the Lucene index to search, as registered in the Xperience Search
     * application. Must be non-empty; validated server-side, which answers 400 Problem Details
     * when it is not.
     */
    index: string;
    /**
     * Language code of the content to search, for example "en". Omit to use the current
     * request's language.
     */
    language?: string;
    /**
     * One-based page number. Defaults to 1, which is the first page.
     */
    page?: number;
    /**
     * Number of results per page. Defaults to 20. The maximum of 1000 is a contract ceiling;
     * the effective maximum is enforced server-side and may be lower per configuration.
     */
    pageSize?: number;
    /**
     * Free-text query. An empty string (the default) means match all documents.
     */
    query?: string;
    /**
     * Client-supplied correlation id echoed back on the response and used to tie click and
     * conversion events to this search. Omit to have the server generate one.
     */
    queryId?: string;
    /**
     * Sort order: the literal "relevance" (the default, score descending) or a sort key
     * configured for the index.
     */
    sort?: string;
}

/**
 * Structured refinements. Omit to search unfiltered.
 *
 * The structured refinements of a search request. Facet and numeric entries are ANDed
 * together; there is no string filter grammar and therefore nothing to escape.
 */
export interface Filters {
    /**
     * Facet refinements, one entry per attribute, ANDed together.
     */
    facets?: FacetFilter[];
    /**
     * Numeric refinements, ANDed together. Dates are compared as Unix epoch seconds.
     */
    numeric?: NumericFilter[];
}

/**
 * The selected values of one facetable attribute. An unknown or non-facetable attribute is
 * a 400 Problem Details keyed by the entry's JSON path, for example
 * filters.facets[0].attribute.
 */
export interface FacetFilter {
    /**
     * Required. The facetable attribute the values belong to, for example "contentType".
     */
    attribute: string;
    /**
     * How the values combine. Defaults to "or".
     */
    operator?: FacetOperator;
    /**
     * Required. The selected values. An empty array refines nothing.
     */
    values: string[];
}

/**
 * How the values combine. Defaults to "or".
 *
 * How the selected values of one facet combine: "or" matches a document carrying any of
 * them, "and" matches only a document carrying all of them.
 */
export type FacetOperator = "or" | "and";

/**
 * One comparison against a numeric or date attribute. An unknown or non-numeric attribute
 * is a 400 Problem Details keyed by the entry's JSON path, for example
 * filters.numeric[0].attribute.
 */
export interface NumericFilter {
    /**
     * Required. The numeric or date attribute to compare, for example "price".
     */
    attribute: string;
    /**
     * Required. The comparison to apply.
     */
    operator: NumericOperator;
    /**
     * Required. The right-hand side of the comparison. A date attribute is compared as Unix
     * epoch seconds.
     */
    value: number;
}

/**
 * Required. The comparison to apply.
 *
 * The comparison of a numeric filter: less than, less than or equal, equal, not equal,
 * greater than or equal, greater than.
 */
export type NumericOperator = "lt" | "lte" | "eq" | "ne" | "gte" | "gt";

/**
 * Highlighting options. Omit to use the defaults.
 *
 * Per-request highlighting configuration.
 */
export interface HighlightOptions {
    /**
     * Fields to produce highlighted snippets for. Results land in Result.highlights.
     */
    fields?: string[];
    /**
     * Markup inserted after each match. Defaults to "</mark>".
     */
    postTag?: string;
    /**
     * Markup inserted before each match. Defaults to "<mark>".
     */
    preTag?: string;
    /**
     * Maximum snippet length in characters. Defaults to 200.
     */
    snippetLength?: number;
}

/**
 * Placeholder property so the code generator emits SearchResponse. Never sent on the wire.
 *
 * Body of a 200 response from POST /api/xpsearch/query.
 */
export interface SearchResponse {
    /**
     * Facet values keyed by attribute name. Only attributes listed in SearchRequest.facets
     * appear, and only values with a non-zero count in the current result set. Each list is
     * ordered by count descending, then by value ascending.
     */
    facets?: { [key: string]: FacetValue[] };
    /**
     * One-based number of the page that was returned.
     */
    page: number;
    /**
     * Page size that was applied, after server-side clamping.
     */
    pageSize: number;
    /**
     * Correlation id for this search. Echoes SearchRequest.queryId when supplied, otherwise
     * server-generated. Send it back on click and conversion events.
     */
    queryId?: string;
    /**
     * Required, and null whenever no redirect rule matched. Set when a relevance rule with the
     * Redirect consequence matched this query; the first such rule in precedence order
     * (priority, then id) wins. The results are still returned alongside it, because following
     * a redirect is the client's decision: the shipped search box navigates only for a query
     * the visitor submitted, never as they type.
     */
    redirect: SearchRedirect | null;
    /**
     * The results on the requested page, in ranked order.
     */
    results: Result[];
    /**
     * Server-side processing time in milliseconds, excluding network time.
     */
    tookMs: number;
    /**
     * Total number of matching documents across all pages.
     */
    total: number;
    /**
     * Total number of pages available.
     */
    totalPages: number;
}

/**
 * The values of one attribute, in display order.
 *
 * One value of one facetable attribute, with the count of matching documents and the text a
 * widget displays for it.
 */
export interface FacetValue {
    /**
     * Required. Number of matching documents carrying this value.
     */
    count: number;
    /**
     * Required. The text to display. For a taxonomy dimension this is the tag title; for any
     * other attribute it equals value.
     */
    label: string;
    /**
     * Optional. For a taxonomy dimension, the code names of the value's ancestors from the root
     * down to its parent, excluding the value itself (["Coffee","Machines"] for Espresso).
     * Absent for a root-level value and for non-taxonomy attributes. Every ancestor named here
     * is itself present in the same facet's values with its own count, so a tree can be built
     * from the values alone.
     */
    path?: string[];
    /**
     * Required. The value to send back in filters.facets. For a taxonomy dimension this is the
     * tag code name.
     */
    value: string;
}

/**
 * Where a matching redirect rule sends the visitor.
 */
export interface SearchRedirect {
    /**
     * Required. Display name of the rule that matched, for logging and for the query tester.
     */
    rule: string;
    /**
     * Required. Destination configured on the rule, exactly as the marketer typed it:
     * root-relative ("/support"), absolute ("https://example.com/support") or any other form
     * the browser can resolve.
     */
    url: string;
}

/**
 * One search result. A closed object: id, score, attributes, highlights and ranking are the
 * only members, so a document field can never collide with a contract member.
 *
 * The document behind this suggestion, present only for indexes that suggest documents.
 */
export interface Result {
    /**
     * Required. The retrieved document fields (title, url, summary, image, ...), whose set is
     * decided by SearchRequest.fields and the index configuration. The only open object in the
     * contract, and the reason the members beside it can never be shadowed. Any attribute
     * holding a link - url is the conventional name - is always root-relative
     * ("/articles/espresso-basics") or absolute
     * ("https://example.com/articles/espresso-basics"); never the app-relative "~/..." form
     * Xperience URL retrievers return, because the server resolves that before the result
     * reaches the wire.
     */
    attributes: { [key: string]: unknown };
    /**
     * Highlighted snippets keyed by field name. Present only for fields requested in
     * SearchRequest.highlight.fields. Values are HTML-encoded content with the configured pre
     * and post tags inserted, so they are safe to render as HTML.
     */
    highlights?: { [key: string]: string };
    /**
     * Required. Stable unique identifier of the indexed document. Send it back on click and
     * conversion events.
     */
    id: string;
    /**
     * Score explanation. Present only when SearchRequest.explain is true; absent otherwise.
     */
    ranking?: RankingInfo;
    /**
     * Final relevance score after boosts and rules. Higher is more relevant; values are only
     * comparable within one response.
     */
    score?: number;
}

/**
 * Score explanation. Present only when SearchRequest.explain is true; absent otherwise.
 *
 * Per-result score explanation, returned only when SearchRequest.explain is true (spec 4.2,
 * 8.4).
 */
export interface RankingInfo {
    /**
     * Lucene score before any boost rule was applied.
     */
    baseScore?: number;
    /**
     * Boosts and rules that changed the score or position, in application order.
     */
    boosts?: string[];
    /**
     * One-based position of this result in the final ranking, across all pages.
     */
    position?: number;
}

/**
 * Placeholder property so the code generator emits SuggestRequest. Never sent on the wire.
 *
 * Body of POST /api/xpsearch/suggest. Whether an index answers with query suggestions or
 * with matching documents is server-side per-index configuration, not a request field.
 */
export interface SuggestRequest {
    /**
     * Required. Code name of the Lucene index to suggest from. Must be non-empty; validated
     * server-side, which answers 400 Problem Details when it is not.
     */
    index: string;
    /**
     * Language code to suggest in, for example "en". Omit to use the current request's language.
     */
    language?: string;
    /**
     * Maximum number of suggestions to return. Defaults to 5. Enforced server-side.
     */
    limit?: number;
    /**
     * Required. The partial input to prefix-match. May be an empty string, which yields no
     * suggestions.
     */
    query: string;
}

/**
 * Placeholder property so the code generator emits SuggestResponse. Never sent on the
 * wire.
 *
 * Body of a 200 response from POST /api/xpsearch/suggest.
 */
export interface SuggestResponse {
    /**
     * Suggestions in display order, at most SuggestRequest.limit of them.
     */
    suggestions: Suggestion[];
}

/**
 * One autocomplete entry.
 */
export interface Suggestion {
    /**
     * The document behind this suggestion, present only for indexes that suggest documents.
     */
    result?: Result;
    /**
     * Required. The text to display and, for a query suggestion, to search for when picked.
     */
    text: string;
    /**
     * Link to follow when the suggestion is picked, present only for indexes that suggest
     * documents. Root-relative or absolute, never the app-relative "~/..." form.
     */
    url?: string;
}
